# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi

import os
from versioncontrol import database

class Find(QtWidgets.QDialog):
    outtext = ''
    def __init__(self, parent=None):
        self.parent = parent
        super().__init__(parent)
        self.setWindowFlags(self.windowFlags() & ~Qt.WindowContextHelpButtonHint)
        loadUi("ui/find.ui", self)

        self.connections()
        self.show()

    def connections(self):
        self.button_Find.clicked.connect(self.find)
        self.button_Cancel.clicked.connect(self.cancel)

    def cancel(self):
        self.hide()
    def find(self):
        self.parent.findText(self.edit_Find.text())